#!/bin/bash -p
# PreToolUse hook (matcher: Read|Edit|Write|MultiEdit|NotebookEdit|Bash|Grep|Glob):
# blocks any tool call that touches ~/.zprofile.secrets, a Keychain-derived
# secrets file generated by the dotfiles restore script and sourced by
# .zprofile. Claude must never read, edit, or echo it. Fixed-substring match
# only — must fail open (exit 0) on any empty/malformed input so unrelated
# tool calls are never blocked.
# This hook is a guardrail against ACCIDENTAL access by the agent: it matches
# the literal path substring in tool inputs. It is not a sandbox and cannot
# stop deliberate multi-step bypasses (symlinks, glob expansion, sourcing
# parent files) — that would require OS-layer enforcement.

set -euo pipefail

HOOK_INPUT=$(/bin/cat 2>/dev/null || echo '{}')

# Opt-out: set CC_GUARD_DISABLE_SECRETS_PATH=1 to disable this hook. Checked after stdin is
# drained so a disabled hook never leaves the harness writing to a closed pipe.
[[ -n "${CC_GUARD_DISABLE_SECRETS_PATH:-}" ]] && exit 0
FILE_PATH=$(printf '%s' "$HOOK_INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
COMMAND=$(printf '%s' "$HOOK_INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null || true)
SEARCH_PATH=$(printf '%s' "$HOOK_INPUT" | jq -r '.tool_input.path // empty' 2>/dev/null || true)

# APFS is case-insensitive by default; match case-insensitively too.
shopt -s nocasematch
if [[ "$FILE_PATH" == *".zprofile.secrets"* || "$COMMAND" == *".zprofile.secrets"* || "$SEARCH_PATH" == *".zprofile.secrets"* ]]; then
  echo "The file ~/.zprofile.secrets holds Keychain-derived secrets and must not be read, edited, or echoed. Ask the operator to verify its configuration without copying secret values into chat or another file." >&2
  exit 2
fi

# Optional development-path policy: leave registered paths in auto mode to the
# normal permissions/harness decision. This is never an allow or ask override.
# Failure or missing system Python preserves the legacy denial below.
SCRIPT_PATH=${BASH_SOURCE[0]}
if [[ "$SCRIPT_PATH" == /* && -x /usr/bin/python3 ]] &&
  ACCESS=$(printf '%s' "$HOOK_INPUT" | /usr/bin/python3 -I -S "${SCRIPT_PATH%/*}/_dev_env_paths.py" 2>/dev/null); then
  if [[ "$ACCESS" == "ABSTAIN" ]]; then
    exit 0
  fi
fi

# .env files hold live secrets; exact template variants (.env.example etc.) do not.
# The .env token must start a path component (start/space/slash/quote/=) so
# code like process.env.HOME is not caught. Inspect every token independently
# so a template token cannot exempt a separate live dotenv token.
ENV_RE='(^|[/[:space:]"'\''=])(\.env(\.[A-Za-z0-9-]+)*)([^A-Za-z0-9_.-]|$)'
for s in "$FILE_PATH" "$COMMAND" "$SEARCH_PATH"; do
  remaining="$s"
  while [[ -n "$remaining" && "$remaining" =~ $ENV_RE ]]; do
    env_token="${BASH_REMATCH[2]}"
    matched="${BASH_REMATCH[0]}"
    case "$env_token" in
      .env.example | .env.sample | .env.template | .env.dist | .env.default | .env.defaults)
        remaining="${remaining#*"$matched"}"
        continue
        ;;
    esac
    echo "Blocked: dotenv path is not designated for development access in auto mode. Consult the template schema or ask the operator to review this exact path. Do not request secret values in chat or copy them to another file. See docs/environment-access.md." >&2
    exit 2
  done
done

exit 0
