#!/usr/bin/env bash
# PreToolUse hook (matcher: Read|Edit|Write|MultiEdit|NotebookEdit|Bash|Grep|Glob):
# blocks any tool call that touches ~/.zprofile.secrets, a Keychain-derived
# secrets file generated by the dotfiles restore script and sourced by
# .zprofile. Claude must never read, edit, or echo it. Fixed-substring match
# only — must fail open (exit 0) on any empty/malformed input so unrelated
# tool calls are never blocked.
# This hook is a guardrail against ACCIDENTAL access by the agent: it matches
# the literal path substring in tool inputs. It is not a sandbox and cannot
# stop deliberate multi-step bypasses (symlinks, glob expansion, sourcing
# parent files) — that would require OS-layer enforcement.

set -euo pipefail

HOOK_INPUT=$(cat 2>/dev/null || echo '{}')

# Opt-out: set CC_GUARD_DISABLE_SECRETS_PATH=1 to disable this hook. Checked after stdin is
# drained so a disabled hook never leaves the harness writing to a closed pipe.
[[ -n "${CC_GUARD_DISABLE_SECRETS_PATH:-}" ]] && exit 0
FILE_PATH=$(printf '%s' "$HOOK_INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
COMMAND=$(printf '%s' "$HOOK_INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null || true)
SEARCH_PATH=$(printf '%s' "$HOOK_INPUT" | jq -r '.tool_input.path // empty' 2>/dev/null || true)

# APFS is case-insensitive by default; match case-insensitively too.
shopt -s nocasematch
if [[ "$FILE_PATH" == *".zprofile.secrets"* || "$COMMAND" == *".zprofile.secrets"* || "$SEARCH_PATH" == *".zprofile.secrets"* ]]; then
  echo "The file ~/.zprofile.secrets holds Keychain-derived secrets and must never be read, edited, or echoed. To confirm a secret exists without opening the file, query the keychain directly: security find-generic-password -a \"\$USER\" -s \"<service>\" -w" >&2
  exit 2
fi

# .env files hold live secrets; template variants (.env.example etc.) do not.
# The .env token must start a path component (start/space/slash/quote/=) so
# code like process.env.HOME is not caught.
# ponytail: a command mixing a template and a real .env (cat .env.example .env)
# slips through the exception; per-token parsing if that ever matters.
ENV_RE='(^|[/[:space:]"'\''=])\.env(\.[A-Za-z0-9-]+)?([^A-Za-z0-9_.-]|$)'
ENV_TEMPLATE_RE='(^|[/[:space:]"'\''=])\.env\.(example|sample|template|dist|defaults?)([^A-Za-z0-9-]|$)'
for s in "$FILE_PATH" "$COMMAND" "$SEARCH_PATH"; do
  if [[ -n "$s" && "$s" =~ $ENV_RE ]] && ! [[ "$s" =~ $ENV_TEMPLATE_RE ]]; then
    echo ".env files hold live secrets and must not be read, edited, or echoed by Claude. Read the template variant (.env.example / .env.sample) instead, or ask the user for the specific value you need." >&2
    exit 2
  fi
done

exit 0
